team-208/colon-front

- app/(pages)/(auth)/login/page.tsx
- app/(pages)/(auth)/signup/page.tsx
- app/(pages)/examples/kakaologin/page.tsx
- app/api/auth/callback/route.ts
- app/api/auth/user/route.ts
- app/api/auth/user/type.d.ts
- app/components/auth/signup/JobGroupList.tsx
- app/hooks/useAuth.ts
- package.json
- yarn.lock
작업내용.
- backend
- fix: auth/callback api 가입 회원 조회 로직 추가.
- feat: auth/user get, post api 추가. (회원 조회 / 가입)
- frontend
- feat: signUp, userInfo 콜백 추가 및 미사용 구문 제거.
- feat: login page api 연동 & signup page api 연동.
- 기타
- feat: lodash 의존성 추가.
- feat: 직군 type 추가 및 기존 comp jobGroup type 대응. 
참고사항.
- 회원 가입 페이지
- 프로필 이미지는 차주 스프린트에서 supabase storage 업로드 구현 후 추가 작업 예정입니다.
- 랜덤 닉네임도 차주 스프린트에서 진행하겠습니다. (open api를 사용 후 추후 개발, 처음부터 직접 개발할지는 공수량을 보고 결정하겠습니다.)
> [feature/task1_26] 카카오 로그인 / 회원가입  api 연동

- app/(pages)/(auth)/login/page.tsx
- app/api/auth/user/route.ts
- app/hooks/useAuth.ts
작업내용.
- fix: user post fail 분기 추가.
- fix: login hook redirectTo 매개 변수 추가.
> [fix/TASK1_34] supabase error

- app/(pages)/examples/storage/page.tsx
- app/api/auth/profile/fetch.ts
- app/api/auth/profile/mutations.ts
- app/api/auth/profile/route.ts
작업내용.
- feat: profile image upload route 추가.
- feat: profile upload fetch 추가.
- feat: profile upload mutation 추가.
- feat: profile upload example 추가.
참고사항.
- post upload는 react quill 데이터 확인 후 별도 이슈로 진행 하겠습니다.
- 회원가입 페이지에 연동은 nick name api 추가 후 함께 연동 작업 하겠습니다.
- 이전 프로젝트 구조에서 react-query 디렉터리를 별도로 관리했었는데 api route와 함께 두는게 file 관리에 용이할 듯 합니다. api 도메인 내부에 api 구현에 필요한 type, fetch, route, query, mutation를 세트로 가지도록 구조 변경 하였습니다.
> [feature/TASk1_36] supabase storage api

- app/components/common/TabsComp.tsx
- app/components/mypage/ActivityContent.tsx
- app/components/mypage/ActivityContentInner.tsx
- app/components/mypage/NicknameComp.tsx
- app/components/mypage/ReactionContent.tsx
- app/components/mypage/ScrapContent.tsx
- app/components/type.d.ts
개발 사항.
- fix: -Content.tsx 파일 내 list 일반변수로 변경
- fix: ActivityContentInner.tsx 컴포넌트 추가
참고 사항.
- components 디렉토리 하위에 type.d.ts 파일 생성하였습니다.
> [fix/task1_18] 마이페이지 별도 이슈 처리

- app/api/auth/deleteUser/fetch.ts
- app/api/auth/deleteUser/mutations.ts
- app/api/auth/profile/fetch.ts
- app/api/auth/user/fetch.ts
- app/api/auth/user/mutations.ts
- app/api/auth/user/queries.ts
- app/api/auth/user/route.ts
- app/api/auth/user/type.d.ts
- app/api/queryKeys.ts
- app/hooks/useAuth.ts
- app/utils/converter.ts
작업내용.
- feat: delete user fetch 분리.
- feat: sign up user fetch 분리, request & response type 추가.
- feat: user session fetch 분리, request & response type, queryhook  추가.
- feat: deleteUser, sign up mutation 추가.
- feat: update user fetch, mutation, route, type 추가.
- feat: removeUndefinedValue util 추가.
- feat: useAuth updateUser 콜백 추가.
- fix
- console.log 제거
- useUserSessionQuery 콜백 명 수정.
- GetUserResponse type 변경 대응.
> [feature/TASK1_39] useAuth 리팩터링

- app/api/auth/nickName/fetch.ts
- app/api/auth/nickName/queries.ts
- app/api/auth/nickName/route.ts
- app/api/auth/nickName/type.d.ts
- app/api/queryKeys.ts
작업내용.
- feat: 랜덤 닉네임 fetch, query, route, type 추가.
참고사항.
- user_info의 nickname column을 unique로 설정 변경했습니다.
> [feature/TASK1_19] 랜덤 닉네임 api

- app/(pages)/(auth)/login/page.tsx
- app/(pages)/(auth)/signup/page.tsx
- app/api/auth/user/route.ts
- app/api/auth/user/type.d.ts
- app/components/auth/signup/ProfileList.tsx
- app/components/auth/signup/SignUpFormComp.tsx
- app/components/common/HeaderComp.tsx
- app/hooks/useAuth.ts
작업내용.
- feat: HeaderComp 로그인 확인용 임시 코드 추가.
- fix: page comp rss로 변경 및 SignUpFormComp 추가.
- fix: get user response kakao 정보 추가.
- feat: 회원가입 페이지 nickname, profileUrl 비즈니스 로직 구현 및 randomNickname api 연동
- fix: user route getUser 제거 & session meta data로 교체 및 kakaoNickname undefined 예외처리
- fix: console.log 제거
> [feature/TASK1_42] 회원가입 api 연동

- app/(pages)/error/404/page.tsx
- app/(pages)/error/500/page.tsx
- app/api/auth/callback/route.ts
- app/api/auth/deleteUser/route.ts
- app/api/auth/nickName/route.ts
- app/api/auth/profile/route.ts
- app/api/auth/user/route.ts
작업내용.
- feat: 임시 404, 500 error page 추가
- fix: /auth/auth-code-error redirect error 500 페이지로 수정.
> [feature/task1_48] 404, 500 route 추가

- app/(pages)/examples/questionCard/page.tsx
- app/components/common/QuestionCard.tsx
- app/components/common/constants.tsx
- app/constants/externalUrls.ts
- app/styles/theme.ts
- next.config.js
작업내용.
- fix: font caption 수정.
- feat: storage image config 설정.
- feat: storage image CDN url constants file 추가.
- feat: JobGroup 관련 constants 추가.
- feat: QuestionCard 퍼블리싱
- feat: QuestionCard example page 추가.
작업내용.
- QuestionCard Props는 post & comment api 추가시 해당  response interface로 대체 될 예정입니다.
> [feature/TASK1_66] 질문 카드 퍼블리싱

- app/(pages)/(board)/qna/[id]/layout.tsx
- app/(pages)/(board)/qna/[id]/page.tsx
- app/(pages)/(board)/qna/layout.tsx
- app/(pages)/(board)/qna/page.tsx
작업내용.
- fix: 중첩 라우팅 관련 layout.tsx, page.tsx 변경.
참고사항.
- layout.tsx, page.tsx 로 전달되는 props에 대해서 제대로 인지하지 못하고 작업해서 생긴 문제였습니다 🥹
> [fix/TASK1-51] routing 별도 이슈 처리.

- app/(pages)/page.tsx
- app/api/auth/callback/route.ts
- app/components/mypage/ProfileComp.tsx
- app/hooks/useAuth.ts
작업내용.
- feat: useAuth userInfo fetch state 속성 추가.
- feat: home page 로그인 유저 진입시 qna 게시판으로 redirect 구문 추가.
- fix: login api 성공시 home -> qna 게시판으로 redirect url 수정.
- fix: mypage userInfo undefined check 구문 추가.
> [feature/TASK1_95] 로그인 유저 QnA 페이지로 바로 이동

- app/(pages)/examples/comment/page.tsx
- app/api/comment/[postId]/fetch.ts
- app/api/comment/[postId]/queries.ts
- app/api/comment/[postId]/route.ts
- app/api/comment/[postId]/type.d.ts
- app/api/comment/fetch.ts
- app/api/comment/mutations.ts
- app/api/comment/route.ts
- app/api/comment/type.d.ts
- app/api/queryKeys.ts
- app/hooks/useAuth.ts
작업내용.
- feat: comment insert fetch, mutation, route, type 추가.
- feat: postId별 comments 조회 fetch, query, route, type, key 추가.
참고사항.
- feat: api 연동, emoji 반응, 글쓴이 채택은 별도 이슈로 진행하겠습니다.
> [feature/TASK1_87] comment api

- app/api/auth/profile/route.ts
- app/components/common/GlobalContainer.tsx
- app/components/common/HeaderComp.tsx
- app/components/mypage/ProfileComp.tsx
- app/components/mypage/ProfileImageComp.tsx
- app/constants/externalUrls.ts
- next.config.js
작업 내용.
- feat: GNB, 마이페이지 profile_url 처리.
- feat: GNB 스크롤 여부 판단 후 블러 처리.
참고 사항.
- 기존 user profile 제거 로직 추가하였습니다. 🙇🏻‍♀️
- 예전에 회원가입 테스트 할때는 profile_url에 자동으로 '/'값이 들어갔는데 현재는 들어가지 않길래, 고려해서 처리했습니다 !
- 임의로 default.png 이미지를 storage에 추가하여 사용했습니다. 회의 때 default 이미지에 대해서 말하겠습니다 !
- storage에 프로필 이미지 파일 저장할 때 파일이름을 캐시문제 때문에 `Math.random()`이용해서 랜덤으로 바꿔주었습니다.
> [feature/TASK1-89] GNB 수정

- app/(pages)/examples/post/page.tsx
- app/api/post/[id]/type.d.ts
- app/api/post/constants.ts
- app/api/post/fetch.ts
- app/api/post/queries.ts
- app/api/post/route.ts
- app/api/post/type.d.ts
- app/api/queryKeys.ts
작업내용.
- feat: post list api query, key, route, fetch, type 추가.
- feat: example post page에 infinity query 예제 추가.
> [feature/TASK1-98] post list 조회 api (4)

- app/(pages)/(board)/qna/[id]/page.tsx
- app/(pages)/examples/comment/page.tsx
- app/api/comment/[postId]/fetch.ts
- app/api/comment/[postId]/route.ts
- app/api/comment/[postId]/type.d.ts
- app/api/comment/route.ts
- app/api/comment/type.d.ts
- app/api/post/[id]/fetch.ts
- app/api/post/[id]/type.d.ts
- app/components/board/qna/QnADetail/QnACommentList.tsx
- app/components/board/qna/QnADetail/QnACommentWrite.tsx
- app/components/board/qna/QnADetail/QnADetailContent.tsx
- app/components/common/CommentComp/Emojis.tsx
- app/components/common/PostComp/Header.tsx
- app/components/common/QuestionCard.tsx
작업내용. 
- feat: post response type 변경.
- feat: post api 연동.
- fix: Emojis comp nullish 대응.
- feat: post accepted_comment_id field 추가.
- feat: comment 조회 api 연동.
- feat: 댓글 등록 api 연동.
- fix: comment 작성자 직군 column 추가 및 대응.
추가내용.
- 이모지 관련 & 댓글 솔팅 & 대댓글 개발은 별도 이슈로 진행하겠습니다.
> [feature/TASK1-100] 상세 페이지 조회 api 연동 (4)

- app/(pages)/(auth)/login/page.tsx
- app/styles/theme.ts
작업내용.
- fix: theme 2.5% 적용 안되는 bug fix.
- feat: 로그인,회원가입 안내 페이지 퍼블리싱
> [feature/TASK1-107] 회원가입 화면 퍼블리싱

- app/(pages)/(board)/qna/[id]/modify/page.tsx
- app/api/post/type.d.ts
- app/components/board/qna/write/WriteFormComp.tsx
- app/components/common/FilterHeaderComp.tsx
- app/components/common/QuillEditor.tsx
작업 내용.
- feat: 글 작성 페이지 api 연동 및 유효성 검사.
- feat: 글 작성 Pending 처리 및 리라우팅 처리.
- feat: 글 수정 페이지 api 연동.
- fix: FilterHeaderComp 버그 수정.
참고 사항.
- FilterHeaderComp에서 버그를 발견하여 수정하였습니다 !
- 저장하기 버튼 누르고 api 호출하고 대기하는 과정에서 대기 화면이 필요할 것 같아서 다음 회의때 말씀드리겠습니다 🙇🏻‍♀️
> [Feature/TASK1-99] 글 작성 페이지 기능 개발 (4)

- app/components/auth/signup/JobGroupList.tsx
- app/components/auth/signup/ProfileList.tsx
- app/components/auth/signup/SignUpFormComp.tsx
작업내용.
- fix: JobGroup button padding override
- fix: 회원가입 화면 프로필 버튼 css 수정.
- feat: 회원가입 화면 하단 블러 이미지 적용.
> [feature/TASK1-86] 회원가입 화면 디자인 QA (3)

- app/(pages)/examples/questionCard/page.tsx
- app/api/post/type.d.ts
- app/components/board/qna/QnaListComp.tsx
- app/components/common/QuestionCard.tsx
작업내용.
- feat: PostListItem id field 추가.
- fix: QuestionCard type PostListItem으로 변경 및 대응.
참고사항.
- instersection observe 적용 & 필터링 적용은 api 수정도 진행되어야해서 별도 이슈로 진행하겠습니다.
> [feature/TASK1-133] 리스트 화면 api 연동

- app/api/post/route.ts
작업내용.
- feat: post 작성 완료시 postId 반환하도록 수정.
> [feature/TASK1-115] 글 작성 완료시 id 반환하도록 api 수정

- app/api/post/search/fetch.ts
- app/api/post/search/queries.ts
- app/api/post/search/route.ts
- app/api/post/search/type.d.ts
- app/api/queryKeys.ts
작업내용.
- feat: post search query, api, fetch, type 추가.
- feat: route 추가.
참고사항.
- 댓글 관련은 추가 작업으로 진행하겠습니다.
> [feature/TASK1-118] 제목 검색 api

- app/(pages)/examples/modal/page.tsx
- app/(pages)/layout.tsx
- app/components/common/ModalComp/Confirm.tsx
- app/components/common/ModalComp/Container.tsx
- app/components/common/ModalComp/index.tsx
- app/hooks/useModal.ts
- app/recoils/key.d.ts
- app/recoils/modal/atom.ts
- app/types/modalType.d.ts
작업 내용.
- feat: modal type, recoil atom, key 추가.
- feat: modal hook 추가.
- feat: modal container 추가 및 적용.
- feat: Modal Confirm comp 추가.
- feat: Modal example page 추가.
> [feature/TASK1-120] 모달 hook comp

- app/(pages)/examples/post/page.tsx
- app/api/post/scrap/fetch.ts
- app/api/post/scrap/mutations.ts
- app/api/post/scrap/queries.ts
- app/api/post/scrap/route.ts
- app/api/post/scrap/type.d.ts
- app/api/queryKeys.ts
- app/components/mypage/ActivityContent.tsx
- app/components/mypage/ReactionContent.tsx
- app/components/mypage/ScrapContent.tsx
작업내용.
- feat: post scrap fetch, mutation, route, type, example 추가.
- feat: script list query key, fetch, route, type, route 추가.
- fix: build fail fix.
> [feature/TASK1-124] scrap 기능 추가

- app/(pages)/(board)/qna/[id]/modify/page.tsx
- app/(pages)/(board)/qna/write/page.tsx
- app/(pages)/mypage/page.tsx
- app/api/post/type.d.ts
- app/components/board/qna/QnaListComp.tsx
- app/components/board/qna/write/TempSaveCompleteModal.tsx
- app/components/board/qna/write/TempSaveModal.tsx
- app/components/board/qna/write/WriteFormComp.tsx
- app/components/board/qna/write/WriteHeader.tsx
- app/components/common/CancelHeader.tsx
- app/components/common/ConfirmHeader.tsx
- app/components/common/ScrollBox.tsx
- app/components/mypage/MypageHeader.tsx
- app/components/mypage/ProfileBox.tsx
- app/hooks/useObserver.ts
- app/recoils/header/atom.ts
- app/recoils/index.ts
- app/recoils/key.d.ts
작업 내용.
- feat: MypageHeader 생성 및 recoil 적용
- feat: WriteHeader 생성 및 recoil 적용
- feat: Observer API 사용 부분 userObserver hook 분리
참고 사항.
- 지난 회의 때 page.tsx 에서 header 관련 state 관리 및 자식 컴포넌트에 props로 데이터를 전달할 수 있는 함수 전달 로직으로 구성하려 했으나, 해당 방식으로 진행하면 마이페이지 page.tsx 를 예시로 header 동작과 관련없는 Tabs 컴포넌트까지 리렌더링되는 문제로 recoil을 사용하여 state를 관리하도록 구성했습니다 :) !
> [feature/TASK1-122] GNB 기능 개발

- app/(pages)/examples/tooltip/page.tsx
- app/(pages)/layout.tsx
- app/components/common/TooltipComp/Basic.tsx
- app/components/common/TooltipComp/Container.tsx
- app/components/common/TooltipComp/index.tsx
- app/hooks/useTooltip.ts
- app/recoils/index.ts
- app/recoils/key.d.ts
- app/recoils/tooltip/atom.ts
- app/types/tooltipType.d.ts
작업 내용.
- feat: TooltipComp Basic, Container 생성 및 퍼블리싱.
- feat: recoil tooltipState atom 추가.
- feat: useTooltip hook 추가.
- feat: Tooltip 예제 페이지 추가.
> [feature/TASK1-147] Tooltip Comp

- app/(pages)/(board)/qna/[id]/modify/page.tsx
- app/(pages)/examples/post/page.tsx
- app/api/post/[id]/fetch.ts
- app/api/post/[id]/mutations.ts
- app/api/post/[id]/route.ts
- app/api/post/[id]/type.d.ts
- app/api/post/route.ts
작업 내용.
- feat: 글 수정 put api 추가.
- feat: post 예제페이지 글 수정 api 추가.
- fix: 글 수정 페이지 TODO 추가.
참고 사항.
- 이슈 타이틀을 임시저장 put api 구현 -> 글 수정 put api 구현으로 변경하였습니다.
> [feature/TASK1-143] 글 수정 put api 구현

- app/api/auth/history/route.ts
작업내용.
- feat: history Get route Scrap 분기 추가.
> [feature/TASK-126] history api scrap 추가

- app/(pages)/(board)/qna/[id]/page.tsx
- app/(pages)/examples/questionCard/page.tsx
- app/api/post/[id]/type.d.ts
- app/api/post/scrap/fetch.ts
- app/components/board/qna/QnADetail/QnADetailContent.tsx
- app/components/board/qna/QnaListComp.tsx
- app/components/common/PostComp/ReactionCount.tsx
- app/components/common/PostComp/ScrapButton.tsx
- app/components/common/PostComp/index.tsx
- app/components/common/QuestionCard.tsx
- app/components/mypage/ActivityContentInner.tsx
- app/components/mypage/ScrapContent.tsx
작업내용.
- fix: GetPostResponse id props 추가.
- fix: 미사용 import 제거.
- fix: fetchInsertPostScrap responst type 수정.
- feat: ReactionCount comp에 scrap 기능 추가 및 comp 사용하는 페이지 대응.
> [Feature/TASK1-139] scrap api 연동

- app/api/auth/history/type.d.ts
- app/api/auth/user/type.d.ts
- app/api/post/type.d.ts
- app/components/board/qna/QnaListComp.tsx
- app/components/board/qna/write/JobGroupList.tsx
- app/components/board/qna/write/WriteFormComp.tsx
- app/components/constants.tsx
작업내용.
- fix: JOB_GROUP_LABELS ALL props 추가.
- fix: JOB_GROUP_TYPES All props 추가 및 대응.
> [feature/TASK1-145] 직군 전체 선택시 노출 처리

- app/api/post/route.ts
작업내용.
- fix: list 조회 order 누락 추가.
> [TASK1-150] order 미적용 버그 수정

- app/components/auth/signup/JobGroupList.tsx
- app/components/board/qna/TopArea.tsx
- app/components/board/qna/write/JobGroupList.tsx
- app/components/common/ButtomComp/Gradient.tsx
- app/components/common/ButtomComp/OutlinedPrimary.tsx
- app/components/common/ButtomComp/Solid.tsx
- app/components/common/ButtomComp/index.tsx
- app/components/common/ButtomComp/style.ts
- app/components/common/ButtomComp/type.d.ts
- app/components/common/ModalComp/Confirm.tsx
작업 내용.
- feat: ButtonComp style.ts. type.d.ts 파일 생성 및 공통 스타일, 타입 분리.
- feat: 공통 스타일, 타입 OutlinedPrimary, Solid 적용.
- feat: Gradient Button 추가 및 ButtonProps interface 변경.
- feat: Gradient Button 적용 및 ButtoComp 적용 컴포넌트 일부 css 변경.
> [feature/TASK1-106] Button comp

- app/(pages)/mypage/page.tsx
- app/components/board/qna/QnADetail/QnADetailContent.tsx
- app/components/common/DividerComp/Vertical.tsx
- app/components/common/DividerComp/index.tsx
- app/components/common/GlobalContainer.tsx
- app/components/common/PostComp/CommentCount.tsx
- app/components/common/PostComp/CountBox.tsx
- app/components/common/PostComp/Header.tsx
- app/components/common/PostComp/MajorBox.tsx
- app/components/common/PostComp/ReactionCount.tsx
- app/components/common/PostComp/index.tsx
- app/components/common/PostComp/type.d.ts
- app/components/common/QuestionCard.tsx
- app/components/mypage/ActivityContentInner.tsx
- app/components/mypage/PostCard.tsx
- app/components/mypage/ScrapContent.tsx
작업 내용.
- fix: PostComp Header MajorP -> MajorBox로 분리 및 적용.
- fix: ReactionCount -> CommentCount, ReactionCount, CountBox로 분리 및 적용
- feat: ReactionCount 퍼블리싱.
참고 사항.
- 기존 ReactionCount에서 CommentCount를 분리하여 두개의 컴포넌트를 CountBox 컴포넌트에서 import해서 사용하는 방식으로 변경하였습니다. 🙇🏻‍♀️
- 데이터가 list보다는 object로 내려오지 않을까 생각하며 작업했습니다. 추후에 변경사항 생기면 변경하겠습니다 !
> [feature/TASK1-160] 반응하기 퍼블리싱

- app/components/common/ModalComp/Container.tsx
작업 내용.
- fix: ModalComp Container 클릭시 modal close 처리 및 버블링 방지
> [feature/TASK1-153] Modal 배경 클릭시 비활성화 처리

- app/api/post/[id]/fetch.ts
- app/api/post/[id]/mutations.ts
- app/api/post/[id]/route.ts
- app/api/post/[id]/type.d.ts
- app/components/board/qna/QnADetail/QnADetailContent.tsx
- app/components/common/Selector.tsx
작업내용.
- feat: Selector selectorButton props 추가 및 options className 추가.
- feat: 글 상세 화면 글쓴이 일 경우 Selector 노출 추가
- feat: post delete fetch, mutations, route, type 추가.
- feat: 글 삭제 기능 추가.
참고사항.
- 글 삭제시 스크랩, 이모지 반응, 댓글 관련 사항은 공수가 좀 들듯해서 별도 이슈로 진행하겠습니다.
- Selector default 값 옵셔널로 바꾸는게 좋을듯한데 이번 이슈와 연관성이 적어 별도 이슈로 백로그 남겨놓겠습니다.
> [feature/TASK1-154] 글 상세 수정 / 삭제 기능 추가

- app/(pages)/(board)/qna/[id]/page.tsx
- app/api/comment/[postId]/queries.ts
- app/api/post/[id]/type.d.ts
- app/components/board/qna/QnADetail/QnACommentList.tsx
작업내용.
- feat: 글쓴이 채택 버튼 퍼블리싱
- fix: GetPostResponse 오탈자 수정
- feat: 답변 채택 api 연동.
참고사항.
- 채택 변경 관련 사항은 기획&디자인 결정시 추가 작업 예정입니다. (https://www.figma.com/design/KYXhapiDZbu5zGCvlLkOI2?node-id=768-1171#848994776)
- 채택 가능 갯수, 상단 노출 교려 필요한 사항에 대해서도 추가 작업 예정입니다. (https://www.figma.com/design/KYXhapiDZbu5zGCvlLkOI2?node-id=43-271#849006426)
> [feature/TAK1-156] 글쓴이 채택 기능 추가

- app/api/comment/[postId]/route.ts
- app/api/comment/fetch.ts
- app/api/comment/mutations.ts
- app/api/comment/route.ts
- app/api/comment/type.d.ts
- app/components/board/qna/QnADetail/CommentItem.tsx
- app/components/board/qna/QnADetail/QnACommentList.tsx
- app/components/common/CommentComp/Header.tsx
- app/components/common/CommentComp/Wrapper.tsx
작업내용.
- fix: 댓글 조회 컬럼 수정.
- feat: CommentItem 분리 및 Comment header Selector 적용.
- feat: 댓글 수정 퍼블리싱.
- feat: comment put fetch, mutation, route, type 추가.
- fix: comment get order id 추가.
- feat: 댓글 수정 api 연동.
참고사항.
- 모달 오픈시 스크롤 되어있는 상태에서는 제대로 open 처리가 되고 있지 않는 현상있습니다. 별도 백로그로 등록해두었습니다.
- Selector 옵션 선택시 close 처리 하거나, open 여부를 set 할수 있는 props 추가 필요할 듯 합니다. 별도 백로그로 등록해두었습니다.
> [feature/TASK1-159] 댓글 수정 기능 추가

- app/components/board/qna/QnADetail/QnACommentList.tsx
작업내용.
- fix: 댓글 정렬 최신순 -> 시간순 문구 변경.
> [feature/TASK1-203] 댓글 최신순 → 시간순으로 text 변경

- app/components/board/qna/write/TagList.tsx
- app/components/board/qna/write/WriteFormComp.tsx
작업 내용.
- fix: 태그 에러 표시 퍼블리싱 및 css 변경.
- feat: TagList 컴포넌트 규칙 적용.
> [feature/TASK1-178] 태그 규칙 적용 및 css 수정

- app/components/board/qna/QnADetail/QnANestedCommentWrite.tsx
작업내용.
- fix: x close button -> 취소 button으로 변경
> [TASK1-206] 대댓글 x → 취소 버튼으로 수정

- app/(pages)/(board)/qna/[id]/page.tsx
- app/components/board/qna/QnADetail/CommentItem.tsx
- app/components/board/qna/QnADetail/QnACommentList.tsx
작업내용.
- feat: 대댓글 입력, 댓글 입력 중 1개만 노출되도록 조건 수정.
> [TASK1-207] 댓글 / 대댓글 입력창 하나만 노출 되도록 수정

- app/api/auth/user/reactions/route.ts
- app/api/post/[id]/fetch.ts
- app/components/board/qna/QnADetail/QnADetailContent.tsx
- app/components/board/qna/write/JobGroupList.tsx
작업 내용.
- fix: reactions 관련 오류 수정 및 글작성시 전체 -> 모두로 텍스트 변경.
참고 사항.
- 제가 저번에 말씀드렸던 에러 관련해서 같이 수정했습니다 ! 확인하시구 승인 부탁드려용 🙇🏻‍♀️
> [feature/TASK1-204] 물어볼 직군 전체 → 모두 로 text 변경

- app/components/common/ButtomComp/Gradient.tsx
- app/components/common/ButtomComp/OutlinedPrimary.tsx
- app/components/common/ButtomComp/Solid.tsx
- app/components/common/ButtomComp/style.ts
- app/components/common/ButtomComp/type.d.ts
- app/components/common/ModalComp/Confirm.tsx
- app/components/common/ModalComp/Container.tsx
- app/hooks/useLockedBody.ts
작업 내용.
- fix: 스크롤 된 상태에서 노출 위치 수정.
- fix: Confirm 모달 Button hover 제거 및 ButtonComp css 변경
- fix: mobile에서 버튼 깨지는 현상 관련 css 수정 및 버튼 사이즈 조정.
> [feature/task1 187] modal 수정

- app/components/common/SearchHeader/DropdownDesktop.tsx
작업 내용.
- feat: 검색드롭다운 css 변경 및 결과없음 처리.
> [feature/TASK1-205] 드롭다운 수정사항

- app/(pages)/(auth)/login/page.tsx
- app/(pages)/page.tsx
- app/components/common/Section.tsx
- app/styles/theme.ts
작업내용.
- feat: login 화면 desktop 퍼블리싱
- feat: 랜딩화면 desktop 퍼블리싱
참고사항.
- desktop 화면만 인터렉션 없이 구현된 상태입니다. 이번주에 많이 못해서 한번에 작업 후 pr 요청 드릴까 고민했는데, 내일 업무가 많아서 회의 참여 어려울거같고 코드양도 꽤 많아서 현재진행사항까지라도 먼저 반영하는게 좋지 않을까 해서 pr 올립니다. 🙇‍♂️
> [feature/TASK1-170] 랜딩, 로그인 페이지 디자인 변경 - desktop

- app/api/post/[id]/reactions/route.ts
- app/api/post/route.ts
- app/api/post/scrap/route.ts
- app/api/post/type.d.ts
- app/components/board/qna/QnaListComp.tsx
작업내용.
- feat: list 조회 order option 추가.
- feat: reaction, scrap시 post count 반영하도록 수정.
참고사항.
- 글상세 반응하기 후, 다시 다른 반응하기 클릭시 로그인 모달 잘못 노출되는 현상 발생중입니다. qa 보드에 따로 이슈등록 해두었습니다.
> [feature/TASK1-123] 리스트 조회 api  sort 필터

- app/api/post/[id]/route.ts
- app/api/post/[id]/type.d.ts
- app/api/post/type.d.ts
- app/components/board/qna/QnADetail/AcceptCommentItem.tsx
- app/components/board/qna/QnADetail/CommentItem.tsx
- app/components/board/qna/QnADetail/QnACommentList.tsx
- app/components/board/qna/QnADetail/QnADetailContent.tsx
- app/components/common/ButtomComp/OutlinedPrimary.tsx
- app/components/common/CommentComp/Reactions.tsx
- app/components/common/QuestionCard.tsx
작업내용.
- feat: 채택 3개까지 가능하도록 api & type 수정.
- fix: OutlinedPrimary inactive css 수정.
- feat: AcceptCommentItem 추가 및 채택 댓글 영역 퍼블리싱.
- feat: 채택 취소 기능 추가.
> [feature/TASK1-174] 댓글 채택 3개 까지로 변경 & 채택 취소 기능

- app/(pages)/examples/icons/page.tsx
- app/components/common/Icon/Icon.tsx
- app/components/common/Icon/svg/ic-arrow.svg
- app/components/common/Icon/svg/index.ts
- next.config.js
- package.json
- yarn.lock
작업내용.
- feat: Icon 공용 comp 추가.
참고사항.
- svg file 들은 다음 스프린트에 추가해두겠습니다. 지금 추가된 arrow는 샘플 파일입니다.
> [TASK1-96] Icon comp

- app/api/auth/history/route.ts
- app/api/auth/history/type.d.ts
- app/components/mypage/ReactionContent.tsx
작업내용.
- feat: HistoryPost userReaction, isScrap type 추가.
- feat: Get history userReaction, isScrap field 추가.
> [feature/TASK1-214] history api scrap & reactions field 추가

- app/components/board/qna/QnADetail/AcceptCommentItem.tsx
- app/components/board/qna/QnADetail/QnACommentList.tsx
> [feature/TASK1-239] 채택답변 디자인 변경

- app/(pages)/(board)/qna/search/page.tsx
- app/api/auth/user/type.d.ts
- app/components/board/qna/search/QnaSearchList.tsx
- app/components/common/HeaderComp/ProfileButton.tsx
- app/components/common/Section.tsx
- app/components/mypage/ProfileBox.tsx
- app/components/mypage/ProfileImage.tsx
작업 내용.
- fix: Section 컴포넌트 관련 css 수정 및 NoSearchBox 관련 화면 처리
- feat: ProfileImage 컴포넌트 Dropdown 적용 및 비즈니스 로직 작성
- fix: QnaSearchList 컴포넌트 오타 수정
참고 사항.
- 지나님이 드롭다운 관련 디자인 주시는거 봐서 변경사항 생기면 별도 이슈로 등록해서 처리하겠습니다 🙇🏻‍♀️
> [feature/TASK1-202] 프로필 수정 사진 변경 드롭다운

- app/components/common/QuillEditor.tsx
작업내용.
- fix: 링크 툴바 선택시 scroll 이동 제거 & bold 미적용 되던 이슈 fix.
참고사항
- QA-11 볼드 기능 같은 editor 이슈라 미적용 함께 처리하였습니다.
> [bugfix/QA-13] 글 작성 시 링크 삽입 기능 오류 & 볼드 기능 미적용

- app/api/post/search/type.d.ts
- app/components/board/qna/QnADetail/AcceptCommentItem.tsx
- app/components/board/qna/QnADetail/CommentItem.tsx
- app/components/board/qna/QnADetail/QnACommentList.tsx
- app/components/board/qna/QnADetail/QnADetailContent.tsx
- app/components/common/CommentComp/Header.tsx
- app/components/common/PostComp/Header.tsx
- app/components/common/QuestionCard.tsx
작업 내용.
- feat: 채택된 댓글 댓글창에 보이지 않도록 로직 추가
- feat: Post, Comment 편집됨 텍스트 로직 처리
- feat: 신고 버튼 추가
참고 사항.
원래는 상세화면 디자인적요소 변경사항 적용하려했는데...! 디자인적으로 변경할 부분은 없어보여서 이슈 내용 바꾸고 수정필요해보이는 로직들 수정했습니다 🙇🏻‍♀️
> [feature/Task1-104] 상세 페이지 전체적인 로직 수정

- app/(pages)/(board)/qna/[id]/page.tsx
- app/api/comment/[postId]/route.ts
- app/api/comment/route.ts
- app/api/post/[id]/route.ts
- app/api/post/route.ts
작업내용.
- feat: post delete is_del update로 변경.
- feat: 삭제된 게시글 조회시 404 이동 로직 추가.
- feat: comment delete is_del update로 변경 & 삭제된 댓글 조회시 분기 처리 추가.
> [feature/TASK1-243] 삭제 로직 재설계 

- app/api/report/fetch.ts
- app/api/report/mutations.ts
- app/api/report/route.ts
- app/api/report/type.d.ts
작업내용.
- feat: 신고하기 post api 추가.
참고사항.
- 신고여부 check api 별도 작업 예정입니다.
> [feature/TASK1-254] 신고하기 post api

- app/api/alarm/fetch.ts
- app/api/alarm/queries.ts
- app/api/alarm/route.ts
- app/api/alarm/type.d.ts
- app/api/queryKeys.ts
작업내용.
- feat: alarm list get fetch, query, route, type, query key 추가.
참고사항.
- 노션 db가 바껴서 prefix 번호가 새로 바뀌어져 있더라구요. 참고 바랍니다. :)
> [feature/TASK-29] 알람 조회 get api

- app/api/report/route.ts
- app/components/board/qna/QnADetail/CommentItem.tsx
- app/components/board/qna/QnADetail/QnADetailContent.tsx
- app/components/board/qna/QnAReportModal.tsx
- app/components/common/CommentComp/Header.tsx
- app/hooks/useReport.ts
> [Feature/TASK-66] 신고하기 api 연동

- app/(pages)/layout.tsx
- app/components/board/qna/QnADetail/QnADetailContent.tsx
- app/components/board/qna/QnAReportModal.tsx
- app/components/common/CommentComp/Header.tsx
- app/components/common/GlobalContainer.tsx
- app/components/common/ModalComp/Confirm.tsx
- app/components/common/ModalComp/Container.tsx
- app/components/common/RouterObserver.tsx
- app/components/common/ScreenCheckBox.tsx
- app/hooks/useModal.ts
- app/recoils/key.d.ts
- app/recoils/modal/atom.ts
- app/recoils/ui/atom.ts
- app/types/modalType.d.ts
- package.json
- yarn.lock
- feat: 모바일 화면 체크 mobileScreenState, ScreenCheckBox 화면 체크 컴포넌트 추가
- feat: 모달 화면 전체로 띄울지 조건 값 isScreen 추가 및 조건에 따른 css 추가
- feat: QnaReportModal 모바일 css 작성
- feat: ScreenCheckBox 화면 리사이즈 이벤트 debounce 적용
- feat: 경로 변경 감지 컴포넌트 생성, 모달창 끄기 로직 추가
> [feature/TASK-73] 신고하기 모달 모바일 작업
